-- Drop existing objects in reverse order to avoid dependency errors
-- This is useful for safely re-running the script
DROP TABLE IF EXISTS "public"."blogs" CASCADE;
DROP SEQUENCE IF EXISTS "public"."blogs_id_seq";

-- Create a sequence for the primary key of the 'blogs' table.
-- Using GENERATED BY DEFAULT AS IDENTITY is a more modern approach (see commented out example below)
-- but sticking to sequence for closer parity to the original script.
CREATE SEQUENCE "public"."blogs_id_seq";

-- Create the 'blogs' table to store blog post information.
CREATE TABLE "public"."blogs" (
    -- 'id' is the primary key, automatically incremented from the sequence.
    "id" INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('blogs_id_seq'::regclass),

    -- For modern PostgreSQL, you might prefer an identity column:
    -- "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "document_id" VARCHAR(255),
    "title" VARCHAR(255),
    "posted" DATE,
    "author" VARCHAR(255),
    "context" JSONB,
    "seo_title" TEXT,
    "seo_description" TEXT,
    "keywords" TEXT,
    "created_at" TIMESTAMP WITHOUT TIME ZONE,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE,
    "published_at" TIMESTAMP WITHOUT TIME ZONE,
    
    -- Foreign key columns referencing the users who created/updated the post.
    -- The actual foreign key constraints are added below.
    "created_by_id" INTEGER,
    "updated_by_id" INTEGER,

    "locale" VARCHAR(255)
);

-- Associate the sequence with the table's 'id' column.
-- This ensures the sequence is automatically dropped if the table or column is dropped.
ALTER SEQUENCE "public"."blogs_id_seq" OWNED BY "public"."blogs"."id";

-- Create indexes to speed up common queries.
CREATE INDEX "blogs_documents_idx" ON "public"."blogs" (document_id, locale, published_at);
CREATE INDEX "blogs_created_by_id_idx" ON "public"."blogs" (created_by_id);
CREATE INDEX "blogs_updated_by_id_idx" ON "public"."blogs" (updated_by_id);

-- ===================================================================================
-- IMPORTANT: Corrected FOREIGN KEY Constraints
-- The original script had invalid syntax. You need to specify the table and column
-- these keys refer to. I am assuming a standard 'users' table with an 'id' column.
-- Please REPLACE 'public.users' and 'id' if your users table is named differently.
-- ===================================================================================
-- ALTER TABLE "public"."blogs" ADD CONSTRAINT "blogs_created_by_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "public"."users"("id") ON DELETE SET NULL;
-- ALTER TABLE "public"."blogs" ADD CONSTRAINT "blogs_updated_by_id_fk" FOREIGN KEY ("updated_by_id") REFERENCES "public"."users"("id") ON DELETE SET NULL;


-- ===================================================================================
-- WARNING: Overly Permissive Grants
-- The following grants give anonymous and authenticated users wide-ranging permissions,
-- including DELETE and TRUNCATE, which is a major security risk.
-- Review these carefully and scope them down to the minimum required permissions.
-- ===================================================================================

-- Permissions for the 'anon' role (unauthenticated users)
GRANT SELECT ON TABLE "public"."blogs" TO "anon";
-- GRANT INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."blogs" TO "anon"; -- Generally unsafe

-- Permissions for the 'authenticated' role (logged-in users)
GRANT SELECT ON TABLE "public"."blogs" TO "authenticated";
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."blogs" TO "authenticated";
-- GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLE "public"."blogs" TO "authenticated"; -- Review if needed

-- Permissions for the 'service_role' (backend/administrative role)
GRANT ALL ON TABLE "public"."blogs" TO "service_role";
